allowBuilds:
  better-sqlite3: true
  electron-winstaller: false
  electron: true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260916.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260916.1'
  - '@cloudflare/workerd-linux-64@1.20260916.1'
  - '@cloudflare/workerd-linux-arm64@1.20260916.1'
  - '@cloudflare/workerd-windows-64@1.20260916.1'
  - workerd@1.20260916.1
overrides:
  workerd: 1.20260916.1
