// The same field contract drives forms, API validation and research import.
export type Field = {
  label: string;
  type?: "text" | "long" | "number" | "json" | "date" | "ref";
  options?: string[];
  ref?: string;
  required?: boolean;
  default?: unknown;
  managed?: boolean;
};
export type Definition = {
  label: string;
  fields: Record<string, Field>;
  claims?: Record<string, string>;
  core?: boolean;
};
const t = (label: string, required = false): Field => ({ label, required });
const l = (label: string): Field => ({ label, type: "long" });
const n = (label: string): Field => ({ label, type: "number" });
const j = (label: string, value: unknown = []): Field => ({
  label,
  type: "json",
  default: value,
});
const e = (label: string, values: string, def?: string): Field => ({
  label,
  options: values.split("|"),
  default: def ?? values.split("|")[0],
});
const r = (label: string, ref: string, required = false): Field => ({
  label,
  type: "ref",
  ref,
  required,
});
const m = (field: Field): Field => ({ ...field, managed: true });
export const requirementKeys = [
  "children_product",
  "kc",
  "trademark_license",
  "parallel_import",
  "copyright_import",
  "design_right",
  "customs_ip_watch",
  "platform_ip_report",
  "listing_assets",
  "customs",
  "labeling",
  "channel_policy",
  "return_policy",
];
export const categories = "plush|plush_keyring|acrylic|stationery|other";
export const stages = [
  "discovered",
  "researching",
  "costing",
  "pricing",
  "listing_ready",
  "live",
  "paused",
  "discontinued",
  "rejected",
  "on_hold",
];
export const catalog: Record<string, Definition> = {
  market_offers: {
    label: "한국 판매처 관찰",
    fields: {
      product_id: r("비교할 상품", "products", true),
      name: t("판매처 이름", true),
      url: t("상품 웹링크", true),
      option_desc: t("옵션·규격", true),
      match_kind: e("상품 일치 여부", "unknown|same|similar"),
      pack_quantity: { ...n("표시 가격의 묶음 수량"), required: true },
      notes: l("일치 판단 근거·배송 조건·메모"),
    },
    claims: { market_price: "money", market_shipping: "money" },
  },
  notes: {
    label: "지식 노트",
    core: true,
    fields: {
      title: t("제목", true),
      type: e(
        "종류",
        "concept|research|competitor_observation|meeting|journal",
        "research",
      ),
      body_md: l("내용"),
      tags_json: j("태그"),
      pinned: { ...n("상단 고정 (1 / 0)"), default: 0 },
    },
  },
  decisions: {
    label: "결정",
    core: true,
    fields: {
      code: t("결정 코드"),
      title: t("제목", true),
      context: l("맥락"),
      decision: t("결정 내용", true),
      rationale: t("이유", true),
      alternatives_json: j("대안 [{option, why_not}]"),
      consequences: l("결과·영향"),
      status: e("상태", "proposed|accepted|superseded|rejected"),
      decided_at: t("결정 시각"),
      revisit_when: t("재검토 조건"),
      revisit_at: { ...t("재검토일"), type: "date" },
      superseded_by: r("후속 결정", "decisions"),
    },
  },
  tasks: {
    label: "할 일·막힘",
    core: true,
    fields: {
      title: t("제목", true),
      detail: l("상세"),
      entity_type: t("관련 기록 종류"),
      entity_id: t("관련 기록 ID"),
      source: m(e("생성 방식", "manual|derived")),
      rule_key: m(t("규칙")),
      status: e("상태", "todo|doing|blocked|done|cancelled"),
      priority: { ...n("우선순위 (1~4)"), default: 3 },
      due_at: t("기한"),
      completed_at: m(t("완료일")),
      blocked_kind: e("막힘 종류", "internal|external|decision"),
      blocked_reason: l("막힘 사유"),
      unblock_condition: t("해제 조건"),
      recheck_at: { ...t("재확인일"), type: "date" },
    },
  },
  sops: {
    label: "업무 절차",
    core: true,
    fields: {
      key: t("절차 키", true),
      title: t("제목", true),
      steps_json: j("단계 [{n, text, check}]"),
      inputs: l("입력 자료"),
      outputs: l("완료 결과"),
      failure_handling: l("실패 시 대응"),
      automation_state: m(e("연동 상태", "none|file|api")),
      job_key: m(t("작업 키")),
    },
  },
  links: {
    label: "기록 연결",
    core: true,
    fields: {
      from_type: t("출발 종류", true),
      from_id: t("출발 ID", true),
      to_type: t("대상 종류", true),
      to_id: t("대상 ID", true),
      relation: e(
        "관계",
        "related|evidence_for|decided_by|supersedes|derived_from|blocks",
      ),
      note: l("연결 이유"),
    },
  },
  fx_rates: {
    label: "환율",
    core: true,
    fields: {
      base_currency: e("통화", "CNY|TWD|USD|JPY|KRW"),
      quote_currency: m(t("환산 통화")),
      rate: t("외화 1단위당 원화", true),
      as_of_date: { ...t("기준일", true), type: "date" },
      kind: e("종류", "manual|reference|card_actual"),
      source: t("출처", true),
      note: l("메모"),
    },
  },
  characters: {
    label: "캐릭터",
    fields: {
      name_ko: t("이름", true),
      name_en: t("영문 이름"),
      notes: l("메모"),
    },
    claims: { rights_holder: "text", kr_licensee: "text" },
  },
  compliance_profiles: {
    label: "판매 요건 프로필",
    fields: {
      name: t("이름", true),
      character_id: r("캐릭터", "characters", true),
      category: e("카테고리", categories),
      model_scope: e(
        "사업 모델 범위",
        "purchase_agency|import_resale|both",
        "both",
      ),
      gate_result: m(e("판정", "unknown|pass|conditional|fail")),
      gate_reason: m(l("판정 이유")),
      gate_set_by: m(e("판정 방식", "derived|manual")),
      reviewed_at: m(t("판정일")),
      recheck_by: { ...t("재확인일"), type: "date" },
    },
  },
  requirement_items: {
    label: "요건 항목",
    fields: {
      profile_id: r("프로필", "compliance_profiles", true),
      key: e("항목", requirementKeys.join("|")),
      question: t("질문", true),
      risk_level: e("위험도", "low|medium|high", "medium"),
      item_result: e("항목 판정", "unknown|pass|conditional|fail"),
      condition_text: l("조건·판정 근거"),
    },
    claims: { answer: "text" },
  },
  products: {
    label: "상품",
    fields: {
      name: t("상품명", true),
      character_id: r("캐릭터", "characters"),
      profile_id: r("판매 요건", "compliance_profiles"),
      category: e("카테고리", categories),
      option_scheme: e("옵션 방식", "designated|random|set"),
      status: m(e("단계", stages.join("|"))),
      status_reason: m(t("변경 사유")),
      stage_entered_at: m(t("단계 진입일")),
      hold_recheck_at: m(t("보류 재검토일")),
      chosen_offer_id: m(r("선택 오퍼", "offers")),
      chosen_scenario_id: r("선택 배송 경로", "shipping_scenarios"),
      current_costing_id: m(r("현재 원가", "costings")),
      pricing_decision_id: m(r("가격 결정", "decisions")),
      competitor_refs: j("경쟁사 관찰 [{url, price, observed_at, note}]"),
      images: j("이미지 URL"),
      notes: l("메모"),
    },
    claims: {
      age_marking: "text",
      decided_price: "money",
      decided_customer_shipping_fee: "money",
      sale_price: "money",
      customer_shipping_fee: "money",
      items_per_order: "number",
      payment_fx_fee: "percent",
      inspection_packaging: "money",
      returns_reserve: "percent",
      ads: "money",
      fixed_costs: "money",
      monthly_units: "number",
    },
  },
  product_variants: {
    label: "상품 옵션",
    fields: {
      product_id: r("상품", "products", true),
      name: t("옵션 이름", true),
      option_kind: e("종류", "designated|random"),
      random_pool_desc: l("랜덤 구성"),
      sku_internal: t("내부 SKU"),
    },
    claims: { weight_g: "number", dims_mm: "text" },
  },
  suppliers: {
    label: "공급처",
    fields: {
      name: t("이름", true),
      name_local: t("현지 이름"),
      platform: e("플랫폼", "taobao|tmall|1688|ruten|other", "other"),
      seller_type: e(
        "판매자 유형",
        "unknown|brand_flagship|authorized|general",
      ),
      store_url: t("매장 URL"),
      country: t("국가"),
      contact_channels: j("연락 방법", {}),
      payment_methods: j("결제 수단"),
      trust_notes: l("신뢰 메모"),
      last_contact_at: t("마지막 연락일"),
    },
    claims: { ships_to_kr: "bool" },
  },
  supplier_messages: {
    label: "공급처 대화",
    fields: {
      supplier_id: r("공급처", "suppliers", true),
      at: t("대화 시각", true),
      direction: e("방향", "in|out"),
      summary: l("대화 내용"),
      attachment_ids: j("첨부 ID"),
    },
  },
  offers: {
    label: "오퍼·견적",
    fields: {
      product_id: r("상품", "products", true),
      supplier_id: r("공급처", "suppliers", true),
      variant_id: r("옵션", "product_variants"),
      url: t("상품 URL"),
      option_desc: l("옵션 설명"),
      option_kind: e("옵션 종류", "unknown|single|set|random|designated"),
      set_composition: l("세트 구성"),
      random_rule: l("랜덤 규칙"),
      quantity_tier_min: n("수량 구간 최소"),
      quantity_tier_max: n("수량 구간 최대"),
      moq: n("최소 주문 수량"),
      currency: e("통화", "CNY|TWD|KRW|USD|JPY"),
      includes_shipping_to: e("배송 포함 범위", "unknown|none|cn_domestic|kr"),
      authenticity_evidence: e(
        "정품 근거",
        "unknown|official_license_mark|authorization_doc|seller_claim|none",
      ),
      status: e("상태", "candidate|verified|rejected|chosen"),
      rejection_reason: l("탈락 사유"),
      decision_id: r("선정 결정", "decisions"),
    },
    claims: {
      listed_price: "money",
      checkout_price: "money",
      cn_domestic_shipping: "money",
      intl_shipping_by_seller: "money",
      lead_time_days: "range",
    },
  },
  forwarders: {
    label: "배송대행 업체",
    fields: {
      name: t("이름", true),
      url: t("홈페이지"),
      warehouse_address: l("창고 주소"),
      currency: e("통화", "CNY|KRW|USD|TWD"),
      notes: l("메모"),
    },
  },
  rate_cards: {
    label: "대행 요율표",
    fields: {
      forwarder_id: r("대행업체", "forwarders", true),
      name: t("이름", true),
      effective_from: { ...t("적용일"), type: "date" },
      weight_bands: j("무게 구간 [{max_g, price_claim_id}]"),
      volumetric_rule: l("부피 무게 규칙"),
      attachment_ids: j("증빙 ID"),
    },
    claims: {
      includes_kr_domestic: "bool",
      customs_handling_fee: "money",
      insurance: "money",
      consolidation_fee: "money",
      repack_fee: "money",
      est_days: "range",
    },
  },
  shipping_scenarios: {
    label: "배송 시나리오",
    fields: {
      product_id: r("상품", "products", true),
      offer_id: r("오퍼", "offers"),
      name: t("이름", true),
      route_type: e("경로", "direct|forwarder"),
      customs_mode: e("통관 방식", "unknown|list_clearance|general"),
      warnings: m(j("중복 비용 경고")),
      is_default: { ...n("기본 경로 (1 / 0)"), default: 0 },
    },
    claims: {
      parcel_items: "number",
      parcel_weight_g: "number",
      duty: "money",
      vat: "money",
      est_total_days: "range",
    },
  },
  shipping_legs: {
    label: "배송 구간",
    fields: {
      scenario_id: r("배송 경로", "shipping_scenarios", true),
      seq: { ...n("구간 순서"), required: true },
      from_node: e("출발", "seller|forwarder_cn|kr_customs|customer_kr"),
      to_node: e("도착", "forwarder_cn|kr_customs|customer_kr", "customer_kr"),
      carrier_or_service: t("배송 서비스"),
      cost_code: e(
        "비용 항목",
        "cn_domestic_shipping|intl_shipping|kr_domestic_shipping|forwarder_fee",
        "intl_shipping",
      ),
      basis: e("비용 기준", "per_parcel|per_kg|per_item|per_order"),
      includes: j("포함 비용 코드"),
      rate_card_id: r("요율표", "rate_cards"),
    },
    claims: { cost: "money", est_days: "range" },
  },
  channels: {
    label: "판매 채널 조건",
    fields: {
      name: t("이름", true),
      type: e("종류", "smartstore|coupang|cafe24|other"),
      account_ref: t("계정 메모"),
      policies: j("정책", {}),
      integration_state: m(e("연동", "none|file|api|error")),
      connector_id: m(t("연동 ID")),
    },
    claims: {
      commission_rate: "percent",
      payment_fee_rate: "percent",
      fee_applies_to_shipping: "bool",
      settlement_cycle: "text",
    },
  },
  readiness_items: {
    label: "사업 준비",
    fields: {
      key: t("체크 키", true),
      title: t("제목", true),
      category: e(
        "영역",
        "decision|legal|tax|customs|channel|finance|logistics|policy|ops",
      ),
      status: e("상태", "not_started|in_progress|blocked|done|not_applicable"),
      depends_on: j("선행 항목 키"),
      evidence: j("증빙 ID"),
      due_at: t("기한"),
      recheck_at: { ...t("재확인일"), type: "date" },
      notes: l("메모"),
      blocks: j("차단 단계"),
    },
  },
  listings: {
    label: "채널 등록 상품",
    fields: {
      channel_id: r("판매 채널", "channels", true),
      product_id: r("상품", "products", true),
      variant_id: r("옵션", "product_variants"),
      external_id: t("채널 상품 번호"),
      url: t("상품 페이지 URL"),
      listed_price: {
        ...j("등록 판매가 {amount_minor, currency}", null),
        label: "등록 판매가 (KRW)",
      },
      customer_shipping_fee: {
        ...j("등록 청구 배송비", null),
        label: "등록 청구 배송비 (KRW)",
      },
      disclosures: j("고지 문구", {}),
      assets_source: e(
        "상세페이지 이미지 출처",
        "unknown|own_photo|licensed|seller_provided_with_permission",
      ),
      status: e("등록 상태", "draft|live|paused|ended"),
      last_verified_at: { ...t("마지막 확인일"), type: "date" },
      costing_id: r("등록 시점 원가 스냅샷", "costings"),
      notes: l("메모"),
    },
  },
  orders: {
    label: "주문",
    fields: {
      channel_id: r("판매 채널", "channels", true),
      listing_id: r("등록 상품", "listings"),
      product_id: r("상품", "products", true),
      variant_id: r("옵션", "product_variants"),
      order_no: t("채널 주문번호", true),
      ordered_at: { ...t("주문일", true), type: "date" },
      qty: { ...n("수량"), required: true, default: 1 },
      status: e(
        "상태",
        "received|ordered|shipped_cn|in_customs|delivered|settled|cancelled|returned",
      ),
      customs_code_collected: e(
        "통관부호 수집 (부호 자체는 저장하지 않음)",
        "unknown|collected|not_needed",
      ),
      supplier_order_no: t("공급처 주문번호"),
      tracking_no: t("송장번호(국제)"),
      delivered_at: { ...t("배송완료일"), type: "date" },
      settled_at: { ...t("정산일"), type: "date" },
      notes: l("메모"),
    },
    claims: {
      customer_paid: "money",
      supplier_paid: "money",
      forwarder_paid: "money",
      settlement_amount: "money",
      refund_amount: "money",
    },
  },
  costings: {
    label: "원가 스냅샷",
    fields: {
      product_id: r("상품", "products", true),
      offer_id: r("오퍼", "offers", true),
      scenario_id: r("시나리오", "shipping_scenarios", true),
      channel_id: r("채널", "channels"),
      qty_assumption: n("소포 수량"),
      items_per_order: n("주문 수량"),
      fx_rate_id: r("환율", "fx_rates"),
      inputs_frozen: j("고정 입력", {}),
      lines: j("항목별 계산"),
      outputs: j("결과", null),
      overall_status: e("상태", "unknown|estimated|confirmed"),
      unknown_keys: j("미확인 입력"),
      is_current: { ...n("현재"), default: 1 },
      decision_id: r("결정", "decisions"),
      note: l("메모"),
    },
  },
};
export const labels: Record<string, string> = {
  same: "동일 상품",
  similar: "유사 상품",
  received: "접수",
  ordered: "발주",
  shipped_cn: "발송",
  in_customs: "통관 중",
  delivered: "배송완료",
  settled: "정산",
  returned: "반품",
  collected: "수집함",
  not_needed: "불필요",
  sent: "발송됨",
  skipped: "미설정",
  failed: "실패",
  confirmed: "확인",
  estimated: "추정",
  unknown: "미확인",
  discovered: "발견",
  researching: "조사",
  costing: "원가 검토",
  pricing: "가격 결정",
  listing_ready: "등록 준비",
  live: "판매 중",
  paused: "중지",
  discontinued: "종료",
  rejected: "탈락",
  on_hold: "보류",
  pass: "통과",
  conditional: "조건부",
  fail: "실패",
  todo: "할 일",
  doing: "진행 중",
  blocked: "막힘",
  done: "완료",
  cancelled: "취소",
  proposed: "제안",
  accepted: "채택",
  superseded: "대체됨",
  not_started: "미시작",
  in_progress: "진행 중",
  not_applicable: "해당 없음",
  plush: "봉제인형",
  plush_keyring: "인형 키링",
  acrylic: "아크릴",
  stationery: "문구",
  other: "기타",
  direct: "직배송",
  forwarder: "배송대행",
  designated: "지정",
  random: "랜덤",
  set: "세트",
  single: "단품",
  candidate: "후보",
  verified: "검증",
  chosen: "선택",
  manual: "수동",
  derived: "규칙",
  none: "없음",
  cn_domestic: "중국 내",
  kr: "한국까지",
  both: "모두",
  purchase_agency: "구매대행",
  import_resale: "수입판매",
  brand_flagship: "브랜드 공식",
  authorized: "인가 판매자",
  general: "일반",
  seller: "판매자",
  forwarder_cn: "중국 대행창고",
  kr_customs: "한국 통관",
  customer_kr: "한국 고객",
  per_parcel: "소포당",
  per_item: "개당",
  per_order: "주문당",
  per_kg: "kg당",
  low: "낮음",
  medium: "중간",
  high: "높음",
  internal: "내부",
  external: "외부",
  decision: "결정",
  concept: "개념",
  research: "조사",
  competitor_observation: "경쟁사 관찰",
  meeting: "대화",
  journal: "일지",
  draft: "등록 준비",
  ended: "등록 종료",
  own_photo: "직접 촬영",
  licensed: "사용 허락 받음",
  seller_provided_with_permission: "판매자 제공(허락)",
  domestic_wholesale: "국내 정식 도매",
  hybrid: "혼합",
  undecided: "미결정",
  unknown_source: "출처 미확인",
};
export const claimLabels: Record<string, string> = {
  market_price: "한국 표시 가격 (묶음 전체)",
  market_shipping: "한국 배송비 (해당 묶음)",
  rights_holder: "권리자",
  kr_licensee: "국내 라이선시",
  answer: "답변",
  age_marking: "연령 표시",
  decided_price: "결정 판매가",
  decided_customer_shipping_fee: "결정 청구 배송비",
  sale_price: "가정 판매가",
  customer_shipping_fee: "고객 청구 배송비",
  items_per_order: "주문당 개수",
  payment_fx_fee: "해외 결제 수수료",
  inspection_packaging: "개당 검수·포장비",
  returns_reserve: "반품 예비율",
  ads: "월 광고비",
  fixed_costs: "월 고정비",
  monthly_units: "예상 월 판매 개수",
  listed_price: "표시가",
  checkout_price: "실결제가",
  customer_paid: "고객 결제액",
  supplier_paid: "공급처 실결제액",
  forwarder_paid: "배대지 결제액",
  settlement_amount: "채널 정산액",
  refund_amount: "환불액",
  cn_domestic_shipping: "중국 내 배송비",
  intl_shipping_by_seller: "판매자 국제배송비",
  lead_time_days: "출고 기간",
  ships_to_kr: "한국 직배송 가능",
  parcel_items: "소포당 개수",
  parcel_weight_g: "소포 무게(g)",
  duty: "소포당 관세",
  vat: "소포당 수입 부가세",
  est_total_days: "전체 배송 기간",
  cost: "구간 배송비",
  est_days: "배송 기간",
  commission_rate: "채널 판매 수수료",
  payment_fee_rate: "결제 수수료",
  fee_applies_to_shipping: "배송비에도 수수료 적용",
  settlement_cycle: "정산 주기",
};
